apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp-ang
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: webapp-ang
        service: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:local-1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp-ang
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp